name: Stranded Kits
version: 1.0
main: me.respawn.strandedkits.Main
author: Respawn
description: A Kit PvP Plugin!

commands:
     kits:
         usage: /<command>
         description: lists the kits